import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import ClientOnly from "./components/ClientOnly";
// import Modal from "./components/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import LoginModal from "./components/modals/LoginModal";
import ToastProvider from "./providers/ToastProvider";
import getCurrentUser from "./actions/getCurrentUser";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});


 export default async function Layout({
   children
   }:{
  children : React.ReactNode
 }) {
  const currentUser=await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToastProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}

