import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import ClientOnly from "./components/ClientOnly";
// import Modal from "./components/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import LoginModal from "./components/modals/LoginModal";
import ToastProvider from "./providers/ToastProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

interface layoutProps {
  children:React.ReactNode
}
 const Layout:React.FC<layoutProps>=({ children })=> {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToastProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}

export default Layout